"""replace_supply_category_with_raw_material_category

Revision ID: 4880fe448c7b
Revises: bacb38abe905
Create Date: 2026-05-31 08:25:32.631573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4880fe448c7b'
down_revision: Union[str, None] = 'bacb38abe905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_raw_material_category',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('raw_category_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['raw_category_code'], ['raw_material_categories.raw_category_code'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'raw_category_code')
    )
    op.drop_table('supplier_category')
    op.drop_table('supply_categories')
    op.alter_column('suppliers', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'address',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('supply_categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='supply_categories_pkey'),
    sa.UniqueConstraint('name', name='supply_categories_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('supplier_category',
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['supply_categories.id'], name='supplier_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='supplier_category_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('supplier_id', 'category_id', name='supplier_category_pkey')
    )
    op.drop_table('supplier_raw_material_category')
    # ### end Alembic commands ###
